# Generated by Django 5.0.7 on 2024-07-22 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_agent_agentworkpermit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="organization",
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
    ]
