# Generated by Django 5.0.7 on 2024-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_agentrepoconnection_delete_agentworkpermit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="repository",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
