# Generated by Django 5.0.7 on 2024-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_alter_agent_id_alter_agentrepoconnection_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="ado_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="status",
            field=models.CharField(
                choices=[("idle", "Idle"), ("working", "Working")],
                default="idle",
                max_length=50,
            ),
        ),
    ]
