# Generated by Django 5.0.7 on 2024-07-22 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0009_repository_git_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="pat_token",
            new_name="pat",
        ),
    ]
