# Generated by Django 5.0.7 on 2024-07-26 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "organization",
            "0011_remove_agent_ado_task_id_agentworksession_agenttask_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="repository",
            old_name="azure_devops_id",
            new_name="source_id",
        ),
    ]
