# Generated by Django 5.0.7 on 2024-07-26 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0012_rename_azure_devops_id_repository_source_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="azure_devops_id",
            new_name="source_id",
        ),
    ]
