# Generated by Django 5.0.7 on 2024-07-31 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0013_rename_azure_devops_id_project_source_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("work_item_source_id", models.CharField(max_length=255)),
                ("pull_request_source_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="agenttask",
            name="ado_task_id",
        ),
        migrations.RemoveField(
            model_name="agenttask",
            name="status",
        ),
        migrations.AddField(
            model_name="agenttask",
            name="work_item",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="organization.workitem",
            ),
            preserve_default=False,
        ),
    ]
