# Generated by Django 5.0.7 on 2024-07-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0015_alter_agenttask_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workitem",
            name="pull_request_source_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
