# Generated by Django 5.0.7 on 2024-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0016_alter_workitem_pull_request_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
