# Generated by Django 5.0.7 on 2024-08-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0017_agenttask_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workitem",
            old_name="status",
            new_name="state",
        ),
        migrations.AlterField(
            model_name="agenttask",
            name="tag",
            field=models.CharField(
                blank=True,
                choices=[("DEV", "Development"), ("PR", "Pull Request")],
                max_length=50,
                null=True,
            ),
        ),
    ]
