# Generated by Django 5.0.7 on 2024-08-21 06:38

import organization.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0018_rename_status_workitem_state_alter_agenttask_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default=organization.models.TaskStatusEnum["PENDING"],
                max_length=50,
            ),
        ),
    ]
