# Generated by Django 5.0.7 on 2024-08-21 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0019_agenttask_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="agent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.agent",
            ),
            preserve_default=False,
        ),
    ]
