version: '3.9'

services:
  postgres:
    image: postgres:13

    volumes:
      - postgres13_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ../../.env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11400:11400"
    environment:
      - OLLAMA_MODEL_PATH=/models
    volumes:
      - ./models:/models

  web:
    container_name: development_workforce
    build:
      context: ../..
      dockerfile: devops/docker/development-workforce.Dockerfile
    command: bash -c "python manage.py collectstatic --noinput && gunicorn development_workforce.wsgi:application --bind 0.0.0.0:8000 --timeout 120"
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    volumes:
      - ../..:/app
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=development_workforce.settings
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  celery_worker:
    build:
      context: ../..
      dockerfile: devops/docker/development-workforce.Dockerfile
    command: celery -A development_workforce worker --loglevel=info
    volumes:
      - ../..:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=development_workforce.settings
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - WORKSPACE_DIR=/app/workspace
    depends_on:
      - redis
      - web
      

  # flower:
  #   image: mher/flower:latest
  #   command: flower --broker=redis://redis:6379/0 --port=5555
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis
  #     - celery_worker

volumes:
  postgres13_data: